export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const LIST_MY_ORDERS_REQUEST = 'LIST_MY_ORDERS_REQUEST';
export const LIST_MY_ORDERS_SUCCESS = 'LIST_MY_ORDERS_SUCCESS';
export const LIST_MY_ORDERS_FAIL = 'LIST_MY_ORDERS_FAIL';
export const LIST_MY_ORDERS_RESET = 'LIST_MY_ORDERS_RESET';

export const ADMIN_GET_ALL_ORDERS_REQUEST = 'ADMIN_GET_ALL_ORDERS_REQUEST';
export const ADMIN_GET_ALL_ORDERS_SUCCESS = 'ADMIN_GET_ALL_ORDERS_SUCCESS';
export const ADMIN_GET_ALL_ORDERS_FAIL = 'ADMIN_GET_ALL_ORDERS_FAIL';

export const ADMIN_OUT_FOR_DELIVERY_REQUEST = 'ADMIN_OUT_FOR_DELIVERY_REQUEST';
export const ADMIN_OUT_FOR_DELIVERY_SUCCESS = 'ADMIN_OUT_FOR_DELIVERY_SUCCESS';
export const ADMIN_OUT_FOR_DELIVERY_FAIL = 'ADMIN_OUT_FOR_DELIVERY_FAIL';
export const ADMIN_OUT_FOR_DELIVERY_RESET = 'ADMIN_OUT_FOR_DELIVERY_RESET';
